openapi: 3.0.0
info:
  title: API Hitorico de Fazendas
  version: 0.1
tags:
  - historico
paths:
  /historicos:
    get:
      tags:
        - historico
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfHistorico'
    post:
      tags:
        - historico
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Historico'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Historico'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
  /historico/{id}:
    get:
      tags:
        - historico
      parameters:
        - in: path
          type: string
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Historico'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    put:
      tags:
        - historico
      parameters:
        - in: path
          type: string
          name: id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Historico'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Historico'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    delete:
      tags:
        - historico
      parameters:
        - in: path
          type: string
          name: id
      responses:
        204:
          content:
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
components:
  schemas:
    ArrayOfHistorico:
      type: array
      items:
        $ref: '#/components/schemas/Historico'
    Historico:
      type: object
      properties:
        nome:
          type: string
        calculo:
          type: number
    Mensagem:
      type: object
      properties:
        msg:
          type: string
