openapi: 3.0.0
info:
  title: Calculo do BioDigestor
  version: 0.0.2
host: localhost:3000
basePath: "/"
tags:
  - Calculos
paths:
  /fazenda:
    post:
      summary: Criar uma nova fazenda
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Farm"
      responses:
        "201":
          description: Fazenda criada com sucesso
        "500":
          description: Erro ao criar a fazenda
    get:
      summary: Listar todas as fazendas
      responses:
        "200":
          description: Lista de fazendas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Farm"
        "500":
          description: Erro ao listar fazendas
  /fazenda/{id}:
    get:
      summary: Obter uma fazenda pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Fazenda encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Farm"
        "404":
          description: Fazenda não encontrada
        "400":
          description: ID inválido
    put:
      summary: Atualizar uma fazenda pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fazendas"
      responses:
        "200":
          description: Fazenda atualizada com sucesso
        "500":
          description: Erro ao atualizar a fazenda
    delete:
      summary: Remover uma fazenda pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Fazenda removida com sucesso
        "500":
          description: Erro ao remover a fazenda
  /calculo:
    get:
      tags:
        - Calculos
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfCalculos"
      security:
        - JWTAuth: []
    post:
      tags:
        - Calculos
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Calculo"
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Calculo"
        422:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mensagem"
  /historico/{id}:
    get:
      tags:
        - historico
      parameters:
        - in: path
          type: string
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Historico"
        404:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mensagem"
        422:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mensagem"
    put:
      tags:
        - historico
      parameters:
        - in: path
          type: string
          name: id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Historico"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Historico"
        404:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mensagem"
    delete:
      tags:
        - historico
      parameters:
        - in: path
          type: string
          name: id
      responses:
        204:
          content:
        404:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mensagem"
components:
  schemas:
    ArrayOfHistorico:
      type: array
      items:
        $ref: "#/components/schemas/Historico"
    Historico:
      type: object
      properties:
        nome:
          type: string
    ArrayOfUsers:
      type: array
      items:
        $ref: "#/components/schemas/Usuario"
    Usuario:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
        senha:
          type: string
    ArrayOfCalculos:
      type: array
      items:
        $ref: "#/components/schemas/Calculo"
    Calculo:
      type: object
      properties:
        nome:
          type: string
        preco:
          type: number
    Mensagem:
      type: object
      properties:
        msg:
          type: string
    Farm:
      type: object
      required:
        - name
        - location
        - size
      properties:
        name:
          type: string
        location:
          type: string
        size:
          type: number
  securitySchemes:
    JWTAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token JWT necessário para autenticação.
