openapi: 3.0.0
info:
<<<<<<< HEAD
  title: API Hitorico de Fazendas
  version: 0.1
host: localhost:3000
basePath:'/api'
tags:
  - historico
paths:
  /historicos:
    get:
      tags:
        - historico
=======
  title: Calculo do BioDigestor
  version: 0.0.2
host: localhost:3000
basePath: '/'
tags:
  - Calculos
paths:
  /api/farms:
    post:
      summary: Criar uma nova fazenda
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Farm'
      responses:
        '201':
          description: Fazenda criada com sucesso
        '500':
          description: Erro ao criar a fazenda
    get:
      summary: Listar todas as fazendas
      responses:
        '200':
          description: Lista de fazendas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Farm'
        '500':
          description: Erro ao listar fazendas
  /api/farms/{id}:
    get:
      summary: Obter uma fazenda pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Fazenda encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Farm'
        '404':
          description: Fazenda não encontrada
        '400':
          description: ID inválido
    put:
      summary: Atualizar uma fazenda pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fazendas'
      responses:
        '200':
          description: Fazenda atualizada com sucesso
        '500':
          description: Erro ao atualizar a fazenda
    delete:
      summary: Remover uma fazenda pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Fazenda removida com sucesso
        '500':
          description: Erro ao remover a fazenda
  /Calculos:
    get:
      tags:
        - Calculos
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
      responses:
        200:
          content:
            application/json:
              schema:
<<<<<<< HEAD
                $ref: '#/components/schemas/ArrayOfHistorico'
=======
                $ref: '#/components/schemas/ArrayOfCalculos'
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
      security:
        - JWTAuth: []
    post:
      tags:
<<<<<<< HEAD
        - historico
=======
        - Calculos
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
      requestBody:
        content:
          application/json:
            schema:
<<<<<<< HEAD
              $ref: '#/components/schemas/Historico'
=======
              $ref: '#/components/schemas/Calculo'
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
      responses:
        201:
          content:
            application/json:
              schema:
<<<<<<< HEAD
                $ref: '#/components/schemas/Historico'
=======
                $ref: '#/components/schemas/Calculo'
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
<<<<<<< HEAD
  /historico/{id}:
    get:
      tags:
        - historico
=======
  /Calculos/{id}:
    get:
      tags:
        - Calculos
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
      parameters:
        - in: path
          type: string
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
<<<<<<< HEAD
                $ref: '#/components/schemas/Historico'
=======
                $ref: '#/components/schemas/Calculo'
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    put:
      tags:
<<<<<<< HEAD
        - historico
=======
        - Calculos
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
      parameters:
        - in: path
          type: string
          name: id
      requestBody:
        content:
          application/json:
            schema:
<<<<<<< HEAD
              $ref: '#/components/schemas/Historico'
=======
              $ref: '#/components/schemas/Calculo'
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
      responses:
        200:
          content:
            application/json:
              schema:
<<<<<<< HEAD
                $ref: '#/components/schemas/Historico'
=======
                $ref: '#/components/schemas/Calculo'
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    delete:
      tags:
<<<<<<< HEAD
        - historico
=======
        - Calculos
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
      parameters:
        - in: path
          type: string
          name: id
      responses:
        204:
          content:
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
components:
  schemas:
<<<<<<< HEAD
    ArrayOfHistorico:
      type: array
      items:
        $ref: '#/components/schemas/Historico'
    Historico:
=======
    ArrayOfCalculos:
      type: array
      items:
        $ref: '#/components/schemas/Calculo'
    Calculo:
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
      type: object
      properties:
        nome:
          type: string
<<<<<<< HEAD
        calculo:
=======
        preco:
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
          type: number
    Mensagem:
      type: object
      properties:
        msg:
          type: string
<<<<<<< HEAD
 securitySchemes: 
=======
    Farm:
      type: object
      required:
        - name
        - location
        - size
      properties:
        name:
          type: string
        location:
          type: string
        size:
          type: number
  securitySchemes: 
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
    JWTAuth:
      type: apiKey
      in: header
      name: Authorization   
<<<<<<< HEAD
      description: Token JWT necessário para autenticação.
=======
      description: Token JWT necessário para autenticação.
    
>>>>>>> 466a0fa0a3b5f8a283de27dc418fbf6641ec8384
